# Generated by Django 5.0.3 on 2024-04-10 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('tag', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('written_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomMOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('android', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('link', models.URLField()),
                ('details', models.TextField()),
                ('upload_date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='mod_comments', to='main.comment')),
                ('credits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.credits')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomROM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('android', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('link', models.URLField(max_length=225)),
                ('details', models.TextField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='rom_comments', to='main.comment')),
                ('credits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.credits')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('device', models.ManyToManyField(blank=True, related_name='custom_roms', to='main.device')),
            ],
        ),
        migrations.CreateModel(
            name='ModComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comment')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_comments', to='main.custommod')),
            ],
        ),
        migrations.CreateModel(
            name='MODLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.custommod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='custommod',
            name='likes',
            field=models.ManyToManyField(related_name='liked_mods', to='main.modlike'),
        ),
        migrations.CreateModel(
            name='RomComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comment')),
                ('rom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rom_comments', to='main.customrom')),
            ],
        ),
        migrations.CreateModel(
            name='ROMLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customrom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customrom',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_roms', to='main.romlike'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authorized', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pictures/akatsuki_logo_xwqj26.png', null=True, upload_to='profile_picture/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
